expose get_period and set_period from rcl
ros2/rclcpp pull request #1020
Opened 2020-03-09 13:23 UTC by ipa-jba

Expose the `std::chrono::nanoseconds get_period()` and `set_period(std::chrono::nanoseconds)` functions of the rcl timers to rclcpp.

reset behaves similar to the reset parameter of ros::Timer::setPeriod

2020-04-01 00:22 UTC, claireyywang commented
what's the benefit of this change?

2020-04-17 06:31 UTC, ipa-jba commented
The perceived benefit from that change came up while porting something like the "twist_mux" from ROS to ROS 2 where one Timer was used as Watchdog, where different input Topics have different durations of being the valid input before falling back to a lower priority input.

Where the ROS Code was
```
    if (prio >= last_prio_) {
      last_prio_ = prio;
      output_.publish(t);
      timer_.setPeriod(decay, true);
    }
```
and used one Timer all the time, the current ROS 2 Code (without this change) creates new timers in every callback 
```
    if (prio >= last_prio_)
    {
      last_prio_ = prio;
      output_->publish(t);
      timer_ = nh_->create_wall_timer(decay, [this]() -> void { last_prio_ = 0; });
```
The intention was to save some allocation/reallocation efforts by reusing an existing timer

2021-01-29 20:42 UTC, ivanpauno requested changes
@ipa-jba Thanks for opening the PR, this addition makes sense to me.

Can you target the PR to `master` instead of eloquent?
Could you add a test case that involves a more real scenario, e.g. modifying period while spinning or modifying the period when some condition happens in the timer callback, etc.

2021-01-31 04:56 UTC, fujitatomoya reviewed
overall lgtm with https://github.com/ros2/rclcpp/pull/1020#pullrequestreview-579603960

2022-06-02 17:21 UTC, fujitatomoya commented
@jabbenseth are you planning to work on this?

2022-10-18 17:29 UTC, clalancette commented
No response to this in quite a long time, so I'm going to go ahead and close it out.  Feel free to reopen if you still want to work on it.

2022-10-18 17:29 UTC, closed without merging