Improve documentation for auto declaration from overrides
ros2/rclcpp pull request #1751
Opened 2021-08-19 10:41 UTC by livanov93

PR makes clear what the `automatically_declare_parameters_from_overrides` flag does and emphasizes that the user should check if parameter already exists on the potential parameter declaration.

PR tackles #1749.

2021-08-20 05:59 UTC, fujitatomoya requested changes

2021-08-20 05:59 UTC, fujitatomoya commented on rclcpp/include/rclcpp/node_options.hpp
> +   * Parameter declaration from overrides is done in the node's base construcor,
nit,

```suggestion
   * Parameter declaration from overrides is done in the node's base constructor,
```

2021-08-23 20:07 UTC, wjwwood commented on rclcpp/include/rclcpp/node_options.hpp
> +   * so user takes care if some parameter is already (e.g. automatically) declared.
```suggestion
   * Parameter declaration from overrides is done in the node's base constructor,
   * so the user must take care to check if the parameter is already (e.g.
   * automatically) declared before declaring it themselves.
```

2021-08-31 16:22 UTC, fujitatomoya approved these changes

2021-09-14 00:35 UTC, wjwwood approved these changes

2021-09-14 00:36 UTC, merged