create a base class for executors entities collectors
ros2/rclcpp pull request #1891
Opened 2022-02-24 15:54 UTC by alsora

Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>

This PR splits the static executor entities collector class into a base and a derived class.
This allows to reuse most of the functionalities when creating new executors.

Both classes are moved to a `detail` subfolder.

2022-02-28 11:51 UTC, alsora commented
Starting CI since github actions is not up to date
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16256)](http://ci.ros2.org/job/ci_linux/16256/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=10877)](http://ci.ros2.org/job/ci_linux-aarch64/10877/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=16615)](http://ci.ros2.org/job/ci_windows/16615/)

2022-03-01 13:24 UTC, alsora commented
New CI

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16271)](http://ci.ros2.org/job/ci_linux/16271/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=10892)](http://ci.ros2.org/job/ci_linux-aarch64/10892/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=16636)](http://ci.ros2.org/job/ci_windows/16636/)

2022-03-09 19:32 UTC, alsora commented
Running again windows.
Failures don't seem to be related.

* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=16674)](http://ci.ros2.org/job/ci_windows/16674/)

2022-03-09 19:34 UTC, clalancette commented
> Failures don't seem to be related.

The previous Windows failure is due to a bug I introduced into the CI scripts that have since been fixed.  Your next attempt should be a lot more successful :).

2022-03-16 18:10 UTC, alsora commented
Hi, can I get a review here?

2022-06-01 10:26 UTC, alsora commented
Hi, can we get a review here?

2022-06-14 16:14 UTC, ivanpauno commented
> Hi, can we get a review here?

I'm starting a review, but it'll take some time until I complete it.

> This PR splits the static executor entities collector class into a base and a derived class.
> This allows to reuse most of the functionalities when creating new executors.

Do you have any concrete example of this?

2022-06-14 16:42 UTC, alsora commented
IMO every executor should use an "entities collector" object, as refreshing the list of entities at every iteration is a huge waste of CPU.
This should be added also to the `SingleThreadedExecutor` allowing to finally get rid of the `StaticSingleThreadedExecutor`.

The `EventsExecutor` will need an entities collector, and it will be implement those virtual functions in a different way since it does not rely on a waitset.
Similarly I expect that other people interested in implementing/designing new executors may want to use this feature

2022-06-23 17:58 UTC, alsora commented
Running CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16884)](http://ci.ros2.org/job/ci_linux/16884/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11454)](http://ci.ros2.org/job/ci_linux-aarch64/11454/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17285)](http://ci.ros2.org/job/ci_windows/17285/)

2022-06-27 21:20 UTC, ivanpauno commented
> IMO every executor should use an "entities collector" object, as refreshing the list of entities at every iteration is a huge waste of CPU.

Agreed.
I think we should clean up all the code related to executors ("entities collector", "memory strategy", etc), and keep only one implementation that works like the current "static executor".

I'm asking for a concrete example of another extension because I don't see how the proposed interfaces in the base class are really useful as an extension point.
Some questions:

- Why not an abstract base class?
- Why were [these methods](https://github.com/ros2/rclcpp/blob/a4311b69c8944f5310ee1e86a755d8f597f88a07/rclcpp/include/rclcpp/executors/detail/entities_collector.hpp#L146-L164) chosen as an extension point?
- Why the base class has some [provided behavior](https://github.com/ros2/rclcpp/blob/a4311b69c8944f5310ee1e86a755d8f597f88a07/rclcpp/include/rclcpp/executors/detail/entities_collector.hpp#L186-L192)? How other executors take advantage of that?

i.e. I need some motivation of the proposed API, as it doesn't seem immediately obvious how other executors would take advantage of it.

2022-06-28 07:32 UTC, alsora commented
See here an example of an additional derived class, used for the events-executor: https://github.com/irobot-ros/events-executor/blob/main/irobot_events_executor/src/rclcpp/executors/events_executor/events_executor_entities_collector.cpp

>  - Why not an abstract base class?
>  - Why were [these methods](https://github.com/ros2/rclcpp/blob/a4311b69c8944f5310ee1e86a755d8f597f88a07/rclcpp/include/rclcpp/executors/detail/entities_collector.hpp#L146-L164) chosen as an extension point?

The entity collector functionalities can be essentially split into two phases.
An entity collector must 1) compute the list of entities from a node or callback group and 2) apply some operations on this list to "connect" the entities  with the executor.
The first item is agnostic with respect to the particular executor implementation, as it only depends on the implementation of nodes and  callback groups.
The main purpose of this PR is to avoid duplicating this first part across different executors, so an abstract base class is not an solution.
The second  part is executor-specific and it's the one that classes derived from the entities collector base must implement through the pure virtual methods you linked above.

>  - Why the base class has some [provided behavior](https://github.com/ros2/rclcpp/blob/a4311b69c8944f5310ee1e86a755d8f597f88a07/rclcpp/include/rclcpp/executors/detail/entities_collector.hpp#L186-L192)? How other executors take advantage of that?

These members of the base class are the "output" of the phase 1) mentioned above. Collected entities end up there and can then be accessed by the derived class for its executor-specific phase 2).

2022-07-12 15:38 UTC, ivanpauno commented
@alsora I looked at the code here and how it's used in https://github.com/irobot-ros/events-executor/blob/main/irobot_events_executor/src/rclcpp/executors/events_executor/events_executor_entities_collector.cpp.
The abstractions are a bit tough to understand and follow, this is partially fault of the current code.
I think we should clean things up if we want this to be maintainable in the future.

Some comments:

- The inteface the executor uses to interact with the entities collector is different for the "static executor" that for the "events executor", e.g. [this](https://github.com/ros2/rclcpp/blob/a4311b69c8944f5310ee1e86a755d8f597f88a07/rclcpp/include/rclcpp/executors/detail/static_executor_entities_collector.hpp#L178) vs [this](https://github.com/irobot-ros/events-executor/blob/c49b672f9596c7e28759d80d89334628d04f41e7/irobot_events_executor/src/rclcpp/executors/events_executor/events_executor_entities_collector.cpp#L336).
  The only methods in common are https://github.com/ros2/rclcpp/blob/a4311b69c8944f5310ee1e86a755d8f597f88a07/rclcpp/include/rclcpp/executors/detail/entities_collector.hpp#L70-L143.
  IMO, the "entities collector" is doing too much.
  We probably need to split some of its functionality in a few classes and use composition instead of inheritance.
- Most of the common logic in the "entities collector" base class is to collect "nodes" and "callback groups".
  That's later used in derived classes to iterate over all entities.
  It would be nices to hava an API to interate over entities, instead of using protected members in the derived classes.
  If not, it seems we're leaking too many details, and implementors of derived class have to basically read the implementation of the base class to understand how everything works.
- How the "static entities collector" interacts with "memory statregy" is also a bit confusing.
  Is memory strategy needed at all? should the "executable list" be filled directly?

I don't have much more time to give more design thoughts on this, but I think it would be better if we see first a proposal of some interfaces and how they interact and later an implementation.

2022-07-12 15:38 UTC, ivanpauno requested changes
see above comment

2022-07-12 15:38 UTC, ivanpauno commented
@wjwwood maybe you're interested on providing feedback here as well

2023-04-29 10:29 UTC, closed without merging