replace future with shared_future
ros2/rclcpp pull request #1974
Opened 2022-07-14 02:18 UTC by iuhilnehc-ynos

It's not mandatory. I would like to keep consistent with the other two methods.

Signed-off-by: Chen Lihui <lihui.chen@sony.com>

2022-07-14 02:27 UTC, iuhilnehc-ynos commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16973)](http://ci.ros2.org/job/ci_linux/16973/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11536)](http://ci.ros2.org/job/ci_linux-aarch64/11536/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17376)](http://ci.ros2.org/job/ci_windows/17376/)

2022-07-14 03:05 UTC, iuhilnehc-ynos commented
Update [[demos]](https://github.com/ros2/demos/pull/569) project. Rerun CI,

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16974)](http://ci.ros2.org/job/ci_linux/16974/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11537)](http://ci.ros2.org/job/ci_linux-aarch64/11537/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17377)](http://ci.ros2.org/job/ci_windows/17377/)

2022-07-14 04:39 UTC, iuhilnehc-ynos commented
It seems there still exist other related repositories that need to be updated.
https://gitlab.com/ros-tracing/ros2_tracing
https://github.com/ros2/system_tests.git

2022-07-14 04:47 UTC, iuhilnehc-ynos commented
For me, I prefer to use the updated source code.

```patch
     // We send the service request for asking the current
     // state of the lc_talker node.
-    auto future_result = client_get_state_->async_send_request(request).future.share();
+    auto future_result = client_get_state_->async_send_request(request);

    // Let's wait until we have the answer from the node.
    // If the request times out, we return an unknown state.
    auto future_status = wait_for_result(future_result, time_out);

``` 

So I'll continue to update other repositories.

2022-07-14 07:43 UTC, iuhilnehc-ynos commented
Updated [ros2_tracing](https://gitlab.com/ros-tracing/ros2_tracing/-/merge_requests/298), run single CI in `Linux-aarch64` successfully

* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11539)](http://ci.ros2.org/job/ci_linux-aarch64/11539/)

And then re-run CI again,

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16975)](http://ci.ros2.org/job/ci_linux/16975/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11540)](http://ci.ros2.org/job/ci_linux-aarch64/11540/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17378)](http://ci.ros2.org/job/ci_windows/17378/)

2022-07-14 16:25 UTC, ivanpauno commented
I don't think this is a good idea.

Consistency doesn't really matter in this case IMO, because you never use the return value in the other cases.
Thye pass a callback as an argument, you really don't need to the returned future (for some reason, we defined the methods like that at some point). And the only reason why that was originally a `shared_future` is because the callbacks receive them as an argument as well https://github.com/ros2/rclcpp/blob/621586ecb0244a6cd60dbeb50adebe7e5206765f/rclcpp/include/rclcpp/client.hpp#L390-L391 

That also doesn't make sense, as they should be getting a reference/pointer to the response directly (there's nothing to be waited when the callback is called, so no need to receive the future as an argument).

IMO, we should clean up the other signatures, instead of modifying the one that seems to make sense for consitency.

2022-07-14 16:25 UTC, ivanpauno requested changes
see above comment

2022-07-15 01:32 UTC, iuhilnehc-ynos commented
As the requested issue is closed, I'll close this PR.
This PR is not going to `clean up the other signatures`.

2022-07-15 01:32 UTC, closed without merging