#2007 fix nullptr dereference in prune_requests_older_than
ros2/rclcpp pull request #2008
Opened 2022-08-30 12:21 UTC by akela1101

2022-08-30 13:13 UTC, alsora approved these changes

2022-08-30 18:05 UTC, fujitatomoya approved these changes

2022-08-30 18:48 UTC, clalancette requested changes
This function is buggy as you point out, so thanks for the fix.

That said, the reason we didn't know it was wrong was that we don't have a test for this function.  Could you add two tests, one of which has `pruned_requests` as nullptr (or just not passed), and one of which has `pruned_requests` as a pointer?

(also, completely orthogonally, why is `pruned_requests` a pointer and not a reference?  Maybe @ivanpauno can chime in since he added this API)

2022-08-30 20:38 UTC, ivanpauno commented
> (also, completely orthogonally, why is pruned_requests a pointer and not a reference? Maybe @ivanpauno can chime in since he added this API)

It's an optional output argument, so the vector isn't used if `nullptr` is provided.
References cannot be nullptr, so they cannot be used in this case.
For some reason I forgot the obvious `if()` in the original PR.

2022-11-23 11:47 UTC, akela1101 commented
@clalancette Sorry for waiting. I tried to add 2 tests, please check.

The way I tested them locally was:
```
colcon build --packages-select rclcpp
colcon test --packages-select rclcpp --ctest-args -R test_client
colcon test-result --verbose
```

2022-11-23 12:05 UTC, alsora approved these changes

2022-11-23 12:28 UTC, ivanpauno approved these changes
lgtm!

2022-11-23 12:28 UTC, ivanpauno commented on rclcpp/test/rclcpp/test_client.cpp
> +  EXPECT_EQ(size_t(1), client->prune_requests_older_than(time));
I would rather use:

```suggestion
  EXPECT_EQ(1u, client->prune_requests_older_than(time));
```

or maybe `size_t{1}`.

2022-11-23 12:28 UTC, ivanpauno commented on rclcpp/test/rclcpp/test_client.cpp
> +  EXPECT_EQ(size_t(1), pruned_requests.size());
```suggestion
  EXPECT_EQ(1u, client->prune_requests_older_than(time, &pruned_requests));
  EXPECT_EQ(1u, pruned_requests.size());
```

2022-11-23 13:32 UTC, akela1101 commented
> 1u

nice suggestion, fixed

2022-11-23 13:46 UTC, ivanpauno approved these changes

2022-11-30 18:26 UTC, fujitatomoya approved these changes

2022-11-30 18:29 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17727)](http://ci.ros2.org/job/ci_linux/17727/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12269)](http://ci.ros2.org/job/ci_linux-aarch64/12269/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18367)](http://ci.ros2.org/job/ci_windows/18367/)

2022-12-01 02:31 UTC, iuhilnehc-ynos commented on rclcpp/test/rclcpp/test_client.cpp
> +  EXPECT_EQ(1u, pruned_requests.size());
```suggestion
  ASSERT_EQ(1u, pruned_requests.size());
  EXPECT_EQ(future.request_id, pruned_requests[0]);
```

2022-12-01 13:49 UTC, ivanpauno commented
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18373)](http://ci.ros2.org/job/ci_windows/18373/)

2022-12-06 20:32 UTC, ivanpauno commented
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18405)](http://ci.ros2.org/job/ci_windows/18405/)

2022-12-13 13:31 UTC, merged

2022-12-13 13:32 UTC, ivanpauno commented
@mergifyio backport humble