Switch lifecycle to use the RCLCPP macros.
ros2/rclcpp pull request #2233
Opened 2023-07-06 13:31 UTC by clalancette

This ensures that they'll go out to /rosout and the disk.

This should fix #2221

2023-07-10 14:03 UTC, ahcorde requested changes
Code is not compiling https://build.ros2.org/job/Rpr__rclcpp__ubuntu_jammy_amd64/947/

2023-07-10 14:06 UTC, clalancette commented
> Code is not compiling https://build.ros2.org/job/Rpr__rclcpp__ubuntu_jammy_amd64/947/

Oh, that's because we need to do a release of `rcl` for this to compile against.  Honestly, we need to do that because all Rpr jobs are failing.  I'll try to get to it later this week.

That said, if we were to run CI from https://ci.ros2.org, this should compile.

2023-07-10 14:09 UTC, ahcorde approved these changes

2023-07-10 18:14 UTC, wjwwood approved these changes

2023-07-10 19:48 UTC, emersonknapp approved these changes

2023-07-10 19:59 UTC, merged

2023-07-24 04:00 UTC, fujitatomoya commented
@clalancette do we want to backport this to iron? or we should backport https://github.com/ros2/rclcpp/pull/2234 to iron?