enable simulation clock for timer canceling test.
ros2/rclcpp pull request #2458
Opened 2024-03-20 17:21 UTC by fujitatomoya

replacement for https://github.com/ros2/rclcpp/pull/2453

this depends on https://github.com/ros2/rclcpp/pull/2456

2024-03-20 17:23 UTC, fujitatomoya commented
CC: @alsora @Crola1702

2024-03-20 19:22 UTC, clalancette requested changes
One thing I think we should change, this otherwise looks good to me.

2024-03-20 19:22 UTC, clalancette commented on rclcpp/test/rclcpp/executors/executor_types.hpp
> +  rclcpp::executors::StaticSingleThreadedExecutor>;
Given that this is only used in `test_executors_timer_cancel_behavior.cpp` for now, I think we can just move it there.  If it turns out we need it in other tests, we can always move it later.

2024-03-20 19:48 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20516)](http://ci.ros2.org/job/ci_linux/20516/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14916)](http://ci.ros2.org/job/ci_linux-aarch64/14916/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21263)](http://ci.ros2.org/job/ci_windows/21263/)

2024-03-20 19:52 UTC, clalancette approved these changes

2024-03-20 23:24 UTC, fujitatomoya commented
yaml_cpp_vendor is failing during clone, i am not sure what the cause this is. retry CI.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20520)](http://ci.ros2.org/job/ci_linux/20520/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21270)](http://ci.ros2.org/job/ci_windows/21270/)

2024-03-21 07:10 UTC, fujitatomoya commented
https://ci.ros2.org/job/ci_windows/21270/testReport/ is unrelated.

2024-03-21 07:10 UTC, merged