Executer regression fix
ros2/rclcpp pull request #2509
Opened 2024-04-17 12:56 UTC by jmachowinski

Fixes https://github.com/ros2/rclcpp/issues/2508

2024-04-17 17:13 UTC, fujitatomoya approved these changes
lgtm!

2024-04-17 17:13 UTC, fujitatomoya commented on rclcpp/test/rclcpp/executors/test_executors.cpp
> +      << "spin_some() took a long time to execute when it should have done "
nitpick: test includes `spin_all` as well.

```suggestion
      << "executor took a long time to execute when it should have done "
```

2024-04-17 20:57 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20877)](http://ci.ros2.org/job/ci_linux/20877/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15180)](http://ci.ros2.org/job/ci_linux-aarch64/15180/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21559)](http://ci.ros2.org/job/ci_windows/21559/)

2024-04-17 21:53 UTC, alsora approved these changes

2024-04-19 09:36 UTC, jmachowinski commented
I looked further into this, as all the tests lid up.
I pushed an updated version, can someone rerun the CI with this ?

@wjwwood @mjcarroll I noticed, that the spin_some_impl method did not act according to the documentation.
It was not recollecting ready executables on every call. Is this intentional, or a bug ?

2024-04-25 16:06 UTC, fujitatomoya commented
@jmachowinski sorry i missed this, here is new CI.

CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20938)](http://ci.ros2.org/job/ci_linux/20938/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15229)](http://ci.ros2.org/job/ci_linux-aarch64/15229/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21612)](http://ci.ros2.org/job/ci_windows/21612/)

2024-04-30 12:41 UTC, wjwwood requested changes
I couldn't fix up this pr directly because of push permissions, but I made a new pr that builds on this one: https://github.com/ros2/rclcpp/pull/2517

I think we should take my pr, but I'm open to discussing even more changes.

2024-05-01 11:23 UTC, wjwwood commented
Closing in favor of https://github.com/ros2/rclcpp/pull/2517, but we can reopen this one if needed.

2024-05-01 11:23 UTC, closed without merging

2024-05-06 16:11 UTC, jmachowinski commented on rclcpp/src/rclcpp/executor.cpp
> +      if (!work_available || !exhaustive) {
You would not end up in this code path as long as work is available, as get_next_ready_executable(any_exec) would return true.