Implement callback support of async_send_request for service generic client
ros2/rclcpp pull request #2614
Opened 2024-08-29 07:25 UTC by Barry-Xu-2018

Currently, the implementation of `async_send_request` for the GenericClient lacks support for callbacks.   
When a response is received, the user-defined callback can be automatically invoked.

2024-08-29 07:45 UTC, ahcorde requested changes

2024-08-29 07:45 UTC, ahcorde commented on rclcpp/test/rclcpp/test_generic_client.cpp
> +  int64_t expected_change = 1111;
include `<cstdint>`

2024-08-29 07:45 UTC, ahcorde commented on rclcpp/test/rclcpp/test_generic_client.cpp
> +    node->create_service<test_msgs::srv::BasicTypes>(service_name, std::move(callback));
include `<utility>`

2024-08-29 07:45 UTC, ahcorde commented on rclcpp/test/rclcpp/test_generic_client.cpp
> +  ASSERT_TRUE(client->wait_for_service(std::chrono::seconds(5)));
include `<chrono>`

2024-08-29 09:39 UTC, Barry-Xu-2018 commented on rclcpp/test/rclcpp/test_generic_client.cpp
> +  int64_t expected_change = 1111;
Thanks, I will add it.

2024-08-29 09:39 UTC, Barry-Xu-2018 commented on rclcpp/test/rclcpp/test_generic_client.cpp
> +    node->create_service<test_msgs::srv::BasicTypes>(service_name, std::move(callback));
This header file already exists.

2024-08-29 09:39 UTC, Barry-Xu-2018 commented on rclcpp/test/rclcpp/test_generic_client.cpp
> +  ASSERT_TRUE(client->wait_for_service(std::chrono::seconds(5)));
I will add it

2024-09-06 00:27 UTC, sloretz commented
@fujitatomoya would you be willing to give this one another review? 🧇

2024-09-11 06:36 UTC, Barry-Xu-2018 commented on rclcpp/test/rclcpp/test_generic_client.cpp
> +TEST_F(TestGenericClientSub, async_send_request_with_request) {
I also considered putting the test in test_client_common.cpp.

In test_client_common.cpp, all tests are based on message "test_msgs/srv/Empty".  A test can be applicable to 2 different types of clients simultaneously.

For the tests in this PR, they need to the message type "test_msgs/srv/BasicTypes". Even if the test moves to test_client_common.cpp, I only want to only test GenericClient.  

So I ended up putting the test in test_generic_client.cpp.

2024-09-18 01:56 UTC, Barry-Xu-2018 commented on rclcpp/test/rclcpp/test_generic_client.cpp
> +TEST_F(TestGenericClientSub, async_send_request_with_request) {
@fujitatomoya Please take a look at my above comments.

2024-09-18 04:30 UTC, fujitatomoya approved these changes
lgtm with green CI

2024-09-18 04:31 UTC, fujitatomoya commented
@ahcorde could you have a 2nd review?

2024-09-18 04:32 UTC, fujitatomoya commented
Pulls: ros2/rclcpp#2614
Gist: https://gist.githubusercontent.com/fujitatomoya/6b080ca006868c0a0419a2a612cd38ae/raw/e03f6ad7967881eacf9d8bc611917e0de0f0701d/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14577
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21854)](http://ci.ros2.org/job/ci_linux/21854/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16124)](http://ci.ros2.org/job/ci_linux-aarch64/16124/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1360)](http://ci.ros2.org/job/ci_linux-rhel/1360/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22565)](http://ci.ros2.org/job/ci_windows/22565/)

2024-09-26 09:02 UTC, Barry-Xu-2018 commented
Missing this information
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22565)](http://ci.ros2.org/job/ci_windows/22565/)  

I will fix this window issue.

2024-09-27 06:14 UTC, Barry-Xu-2018 commented
Re-run CI on Windows

* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22625)](http://ci.ros2.org/job/ci_windows/22625/)

2024-09-27 14:57 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21907)](http://ci.ros2.org/job/ci_linux/21907/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16175)](http://ci.ros2.org/job/ci_linux-aarch64/16175/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1416)](http://ci.ros2.org/job/ci_linux-rhel/1416/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22628)](http://ci.ros2.org/job/ci_windows/22628/)

2024-09-27 14:57 UTC, ahcorde approved these changes

2024-10-04 10:12 UTC, merged