fix: Fixed race condition in action server between is_ready and take (humble)
ros2/rclcpp pull request #2635
Opened 2024-09-30 21:56 UTC by edgarcamilocamacho

Related bug: #2242. I managed to create a situation in which I can easily replicate it as many times as I wanted.

This bug was already fixed in rolling (#2495) and iron (#2531).

I just backported the fix based on the iron fix. Now I test it and works perfectly all the times I run my node.

I tried to do it as clean as possible (fortunately the iron fix didn't touch header filed and all the function prototypes where the same between iron and humble).

2024-10-01 11:24 UTC, jmachowinski requested changes

2024-10-01 11:24 UTC, jmachowinski commented on rclcpp_action/src/client.cpp
> +    // there is a known bug in iron, that take_data might be called multiple
This bug should not be present in Humble, therefore in the humble version there should be a throw, to avoid covering other bugs.

2024-10-01 11:24 UTC, jmachowinski commented on rclcpp_action/src/client.cpp
> +    // workaround, if take_data was called multiple timed, it returns a nullptr
Same here, if a null pointer gets passed to execute, we should throw.

2024-10-01 11:24 UTC, jmachowinski commented on rclcpp_action/src/server.cpp
> +    // there is a known bug in iron, that take_data might be called multiple
replace by throw

2024-10-01 11:24 UTC, jmachowinski commented on rclcpp_action/src/server.cpp
> +    // workaround, if take_data was called multiple timed, it returns a nullptr
replace by throw

2024-10-10 17:10 UTC, mjcarroll commented
This also needs DCO sign-off.

2024-10-10 17:56 UTC, fujitatomoya reviewed
@edgarcamilocamacho friendly ping

2024-10-25 15:22 UTC, edgarcamilocamacho commented
I changed the `return nullptr;` lines to be `throw`, let me know if the messages are correct.

2024-10-25 21:20 UTC, fujitatomoya commented
@edgarcamilocamacho this still needs DCO signoff.

2024-10-25 21:21 UTC, fujitatomoya commented
@jmachowinski all comments are addressed, could you take an another round?

2024-10-26 10:21 UTC, jmachowinski commented
I will have a look on Monday. 
@edgarcamilocamacho fyi for the dco to succeed you need to squash the commits and in git gui (or similar tool) press the signoff button. Afterwards you need to force push your branch.

2024-10-28 12:32 UTC, jmachowinski approved these changes

2024-10-28 12:35 UTC, jmachowinski commented
Looks good to me, just the DCO missing. Perhaps also add me as co author as this is a cherry pick of my patch. (I personally don't care, but don't know what the ros policy on this kind of stuff is...)

2024-10-28 19:16 UTC, edgarcamilocamacho commented
Done, sorry if you received multiple notifications, I had a problem with my company and personal emails and did multiple push while fixing it.

2024-10-29 08:05 UTC, jmachowinski commented
@fujitatomoya can you run the full CI ?

2024-10-29 08:11 UTC, ahcorde commented
Pulls: ros2/rclcpp#2635
Gist: https://gist.githubusercontent.com/ahcorde/95876fd74a3156cdb63d5811a4a0b919/raw/092e6f72f4ae138cef880177361c4e6ac8abe767/ros2.repos
BUILD args:   --packages-above-and-dependencies rclcpp_action --packages-above-and-dependencies rclcpp_action
TEST args:  --packages-above rclcpp_action --packages-above rclcpp_action
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14740
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22043)](http://ci.ros2.org/job/ci_linux/22043/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16297)](http://ci.ros2.org/job/ci_linux-aarch64/16297/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1561)](http://ci.ros2.org/job/ci_linux-rhel/1561/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22773)](http://ci.ros2.org/job/ci_windows/22773/)

2024-10-29 09:01 UTC, jmachowinski commented
@ahcorde Thx for the CI run. The Gist is wrong though, it points to rolling, but must point to humble...

2024-10-29 11:44 UTC, ahcorde commented
Pulls: ros2/rclcpp#2635
Gist: https://gist.githubusercontent.com/ahcorde/b6a81a1a37a81db618aed4554f7ff3fe/raw/93c6af7e44abd34eab68bcb9f12196fd45125d2a/ros2.repos
BUILD args:   --packages-above-and-dependencies rclcpp_action --packages-above-and-dependencies rclcpp_action
TEST args:  --packages-above rclcpp_action --packages-above rclcpp_action
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14741
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22044)](http://ci.ros2.org/job/ci_linux/22044/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16298)](http://ci.ros2.org/job/ci_linux-aarch64/16298/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1562)](http://ci.ros2.org/job/ci_linux-rhel/1562/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22774)](http://ci.ros2.org/job/ci_windows/22774/)

2024-10-31 09:03 UTC, ahcorde approved these changes

2024-10-31 09:03 UTC, merged