Update docstring for `rclcpp::Node::now()` and `rclcpp::LifecycleNode::now()`
ros2/rclcpp pull request #2696
Opened 2024-12-03 14:27 UTC by roncapat

2024-12-03 18:21 UTC, fujitatomoya requested changes

2024-12-03 18:21 UTC, fujitatomoya commented on rclcpp/include/rclcpp/node.hpp
> +  /// Returns current time from the node time source.
i agree to remove `clock_type` from here, but technically it is not always come from time source.

```suggestion
  /// Returns current time from the node clock.
```

2024-12-03 18:21 UTC, fujitatomoya commented on rclcpp/include/rclcpp/node.hpp
> +   *
i do not think this is the correct description, if the Node is constructed with `options.clock_type(RCL_SYSTEM_TIME)` or `options.clock_type(RCL_STEADY_TIME)`. i would remove this description.

```suggestion
```

2024-12-04 16:30 UTC, fujitatomoya approved these changes
lgtm.

@roncapat DCO missing, can you fix that?

2024-12-04 16:33 UTC, roncapat commented
Done :)

2024-12-04 17:24 UTC, merged