fix TestTimeSource.ROS_time_valid_attach_detach.
ros2/rclcpp pull request #2700
Opened 2024-12-07 16:01 UTC by fujitatomoya

This PR fixes the `TestTimeSource.ROS_time_valid_attach_detach` error message below.
This test is expected to call `detachClock` with valid operation to remove the clock successfully.

- before

```bash
colcon test --event-handlers console_direct+ --packages-select rclcpp --ctest-args -R test_time_source
...
89: [ RUN      ] TestTimeSource.ROS_time_valid_attach_detach
89: [ERROR] [1733531284.881187504] [rclcpp]: failed to remove clock
89: [       OK ] TestTimeSource.ROS_time_valid_attach_detach (4 ms)
...
```

- after

```bash
colcon test --event-handlers console_direct+ --packages-select rclcpp --ctest-args -R test_time_source
...
89: [ RUN      ] TestTimeSource.ROS_time_valid_attach_detach
89: [       OK ] TestTimeSource.ROS_time_valid_attach_detach (4 ms)
...
```

2024-12-07 16:02 UTC, fujitatomoya reviewed
@clalancette @ahcorde minor test fix, can you take a look?

2024-12-07 16:02 UTC, fujitatomoya commented on rclcpp/test/rclcpp/test_time_source.cpp
> +  ts.attachClock(ros_clock);
clock needs to be added once again here before `detachClock`, because `detachNode` clears node state with associated clocks already.

2024-12-07 16:03 UTC, fujitatomoya commented
Pulls: ros2/rclcpp#2700
Gist: https://gist.githubusercontent.com/fujitatomoya/80a4c05801a71c9dda7040a25935f046/raw/ca3eefe31e51cb3c2f5f54be3e67bf697e27716b/ros2.repos
BUILD args:  --packages-up-to rclcpp
TEST args:  --packages-select rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14915
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22227)](http://ci.ros2.org/job/ci_linux/22227/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16487)](http://ci.ros2.org/job/ci_linux-aarch64/16487/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1749)](http://ci.ros2.org/job/ci_linux-rhel/1749/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22992)](http://ci.ros2.org/job/ci_windows/22992/)

2024-12-07 20:11 UTC, clalancette requested changes

2024-12-07 20:11 UTC, clalancette commented on rclcpp/test/rclcpp/test_time_source.cpp
> +  EXPECT_FALSE(ros_clock->ros_time_is_active());
This is duplicated with the check 2 lines above, so we don't need this.

```suggestion
```

2024-12-07 22:00 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22228)](http://ci.ros2.org/job/ci_linux/22228/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16488)](http://ci.ros2.org/job/ci_linux-aarch64/16488/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1750)](http://ci.ros2.org/job/ci_linux-rhel/1750/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22994)](http://ci.ros2.org/job/ci_windows/22994/)

2024-12-09 18:32 UTC, fujitatomoya commented
@clalancette friendly ping

2024-12-09 19:33 UTC, clalancette approved these changes

2024-12-09 21:15 UTC, merged